const campaign_content = [
  {
    _id: 1,
    name: "fond for floods",
    limit: 40000,
    collected: 29986,
    about:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Et sunt vel beatae quidem facilis harum animi ad alias cumque tempora?",
    category: "emergency",
    img_url: require("./images/campaign-1.jpg"),
  },
  {
    _id: 2,
    name: "accident",
    limit: 62500,
    collected: 35000,
    about:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Et sunt vel beatae quidem facilis harum animi ad alias cumque tempora?",
    category: "emergency",
    img_url: require("./images/campaign-2.jpg"),
  },
  {
    _id: 3,
    name: "help old people",
    limit: 32550,
    collected: 10000,
    about:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Et sunt vel beatae quidem facilis harum animi ad alias cumque tempora?",
    category: "orphanges",
    img_url: require("./images/campaign-3.jpg"),
  },
  {
    _id: 4,
    name: "child education",
    limit: 40500,
    collected: 12000,
    about:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Et sunt vel beatae quidem facilis harum animi ad alias cumque tempora?",
    category: "education",
    img_url: require("./images/campaign-4.jpg"),
  },
  {
    _id: 5,
    name: "animal welfare relief",
    limit: 46500,
    collected: 45000,
    about:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Et sunt vel beatae quidem facilis harum animi ad alias cumque tempora?",
    category: "others",
    img_url: require("./images/campaign-5.jpg"),
  },
];
const campaign_table = [
  {
    id: "1",
    name: "Funds for Animals",
    details:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptates ratione beatae facilis modi officiis incidunt laborum sed qui iusto voluptas.",
    address: "31/1079-8, Teacher's Colony",
    state: "Andhra Pradesh",
    email: "fundraiser@gmail.com",
    category: "animals",
  },
  {
    id: "2",
    name: "Funds for Animals",
    details:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptates ratione beatae facilis modi officiis incidunt laborum sed qui iusto voluptas.",
    address: "31/1079-8, Teacher's Colony",
    state: "Andhra Pradesh",
    email: "fundraiser@gmail.com",
    category: "animals",
  },
  {
    id: "3",
    name: "Funds for Animals",
    details:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptates ratione beatae facilis modi officiis incidunt laborum sed qui iusto voluptas.",
    address: "31/1079-8, Teacher's Colony",
    state: "Andhra Pradesh",
    email: "fundraiser@gmail.com",
    category: "animals",
  },
  {
    id: "4",
    name: "Funds for Animals",
    details:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptates ratione beatae facilis modi officiis incidunt laborum sed qui iusto voluptas.",
    address: "31/1079-8, Teacher's Colony",
    state: "Andhra Pradesh",
    email: "fundraiser@gmail.com",
    category: "animals",
  },
  {
    id: "5",
    name: "Funds for Animals",
    details:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptates ratione beatae facilis modi officiis incidunt laborum sed qui iusto voluptas.",
    address: "31/1079-8, Teacher's Colony",
    state: "Andhra Pradesh",
    email: "fundraiser@gmail.com",
    category: "animals",
  },
  {
    id: "6",
    name: "Funds for Animals",
    details:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptates ratione beatae facilis modi officiis incidunt laborum sed qui iusto voluptas.",
    address: "31/1079-8, Teacher's Colony",
    state: "Andhra Pradesh",
    email: "fundraiser@gmail.com",
    category: "animals",
  },
  {
    id: "7",
    name: "Funds for Animals",
    details:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptates ratione beatae facilis modi officiis incidunt laborum sed qui iusto voluptas.",
    address: "31/1079-8, Teacher's Colony",
    state: "Andhra Pradesh",
    email: "fundraiser@gmail.com",
    category: "animals",
  },
  {
    id: "8",
    name: "Funds for Animals",
    details:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptates ratione beatae facilis modi officiis incidunt laborum sed qui iusto voluptas.",
    address: "31/1079-8, Teacher's Colony",
    state: "Andhra Pradesh",
    email: "fundraiser@gmail.com",
    category: "animals",
  },
  {
    id: "9",
    name: "Funds for Animals",
    details:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptates ratione beatae facilis modi officiis incidunt laborum sed qui iusto voluptas.",
    address: "31/1079-8, Teacher's Colony",
    state: "Andhra Pradesh",
    email: "fundraiser@gmail.com",
    category: "animals",
  },
  {
    id: "10",
    name: "Funds for Animals",
    details:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptates ratione beatae facilis modi officiis incidunt laborum sed qui iusto voluptas.",
    address: "31/1079-8, Teacher's Colony",
    state: "Andhra Pradesh",
    email: "fundraiser@gmail.com",
    category: "animals",
  },
  {
    id: "11",
    name: "Funds for Animals",
    details:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptates ratione beatae facilis modi officiis incidunt laborum sed qui iusto voluptas.",
    address: "31/1079-8, Teacher's Colony",
    state: "Andhra Pradesh",
    email: "fundraiser@gmail.com",
    category: "animals",
  },
  {
    id: "12",
    name: "Funds for Animals",
    details:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptates ratione beatae facilis modi officiis incidunt laborum sed qui iusto voluptas.",
    address: "31/1079-8, Teacher's Colony",
    state: "Andhra Pradesh",
    email: "fundraiser@gmail.com",
    category: "animals",
  },
];
const dontation_table = [
  {
    id: "1",
    campaign: "Funds for Animals",
    donar: "Donar Demo1",
    donated_amount: "1000.00",
    donated_on: "05-05-2001",
    email: "fundraiser@gmail.com",
  },
  {
    id: "2",
    campaign: "Funds for Animals",
    donar: "Donar Demo1",
    donated_amount: "1000.00",
    donated_on: "05-05-2001",
    email: "fundraiser@gmail.com",
  },
  {
    id: "3",
    campaign: "Funds for Animals",
    donar: "Donar Demo1",
    donated_amount: "1000.00",
    donated_on: "05-05-2001",
    email: "fundraiser@gmail.com",
  },
  {
    id: "4",
    campaign: "Funds for Animals",
    donar: "Donar Demo1",
    donated_amount: "1000.00",
    donated_on: "05-05-2001",
    email: "fundraiser@gmail.com",
  },
  {
    id: "5",
    campaign: "Funds for Animals",
    donar: "Donar Demo1",
    donated_amount: "1000.00",
    donated_on: "05-05-2001",
    email: "fundraiser@gmail.com",
  },
  {
    id: "6",
    campaign: "Funds for Animals",
    donar: "Donar Demo1",
    donated_amount: "1000.00",
    donated_on: "05-05-2001",
    email: "fundraiser@gmail.com",
  },
  {
    id: "7",
    campaign: "Funds for Animals",
    donar: "Donar Demo1",
    donated_amount: "1000.00",
    donated_on: "05-05-2001",
    email: "fundraiser@gmail.com",
  },
  {
    id: "8",
    campaign: "Funds for Animals",
    donar: "Donar Demo1",
    donated_amount: "1000.00",
    donated_on: "05-05-2001",
    email: "fundraiser@gmail.com",
  },
  {
    id: "9",
    campaign: "Funds for Animals",
    donar: "Donar Demo1",
    donated_amount: "1000.00",
    donated_on: "05-05-2001",
    email: "fundraiser@gmail.com",
  },
  {
    id: "10",
    campaign: "Funds for Animals",
    donar: "Donar Demo1",
    donated_amount: "1000.00",
    donated_on: "05-05-2001",
    email: "fundraiser@gmail.com",
  },
  {
    id: "11",
    campaign: "Funds for Animals",
    donar: "Donar Demo1",
    donated_amount: "1000.00",
    donated_on: "05-05-2001",
    email: "fundraiser@gmail.com",
  },
  {
    id: "12",
    campaign: "Funds for Animals",
    donar: "Donar Demo1",
    donated_amount: "1000.00",
    donated_on: "05-05-2001",
    email: "fundraiser@gmail.com",
  },
];

const users_table = [
  {
    id: "1",
    name: "Demo user1",
    contact_no: "9995656891",
    role: "Fund Raiser",
    created_date: "05-05-2001",
    status: "Active",
    email: "fundraiser@gmail.com",
  },
  {
    id: "2",
    name: "Demo user1",
    contact_no: "9995656891",
    role: "Fund Raiser",
    created_date: "05-05-2001",
    status: "Active",
    email: "fundraiser@gmail.com",
  },
  {
    id: "3",
    name: "Demo user1",
    contact_no: "9995656891",
    role: "Fund Raiser",
    created_date: "05-05-2001",
    status: "Active",
    email: "fundraiser@gmail.com",
  },
  {
    id: "4",
    name: "Demo user1",
    contact_no: "9995656891",
    role: "Fund Raiser",
    created_date: "05-05-2001",
    status: "Active",
    email: "fundraiser@gmail.com",
  },
  {
    id: "5",
    name: "Demo user1",
    contact_no: "9995656891",
    role: "Fund Raiser",
    created_date: "05-05-2001",
    status: "Active",
    email: "fundraiser@gmail.com",
  },
  {
    id: "6",
    name: "Demo user1",
    contact_no: "9995656891",
    role: "Fund Raiser",
    created_date: "05-05-2001",
    status: "Active",
    email: "fundraiser@gmail.com",
  },
  {
    id: "7",
    name: "Demo user1",
    contact_no: "9995656891",
    role: "Fund Raiser",
    created_date: "05-05-2001",
    status: "Active",
    email: "fundraiser@gmail.com",
  },
  {
    id: "8",
    name: "Demo user1",
    contact_no: "9995656891",
    role: "Fund Raiser",
    created_date: "05-05-2001",
    status: "Active",
    email: "fundraiser@gmail.com",
  },
  {
    id: "9",
    name: "Demo user1",
    contact_no: "9995656891",
    role: "Fund Raiser",
    created_date: "05-05-2001",
    status: "Active",
    email: "fundraiser@gmail.com",
  },
  {
    id: "10",
    name: "Demo user1",
    contact_no: "9995656891",
    role: "Fund Raiser",
    created_date: "05-05-2001",
    status: "Active",
    email: "fundraiser@gmail.com",
  },
  {
    id: "11",
    name: "Demo user1",
    contact_no: "9995656891",
    role: "Fund Raiser",
    created_date: "05-05-2001",
    status: "Active",
    email: "fundraiser@gmail.com",
  },
  {
    id: "12",
    name: "Demo user1",
    contact_no: "9995656891",
    role: "Fund Raiser",
    created_date: "05-05-2001",
    status: "Active",
    email: "fundraiser@gmail.com",
  },
];
export { dontation_table, campaign_table, users_table };
export default campaign_content;
